### ISSUE TITLE
Unable to start WHIP

### ISSUE THREAD

**Issue by eric-gitta-moore** [Tencent-RTC/obs-trtc#2]
I got "Could not access the specified channel or stream key,please double-check your stream key.If it is correct,there may be a problem connecting to the server."

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/8b34cc0b-0cc9-4868-8371-c72a0816f95e">

<img width="981" alt="image" src="https://github.com/user-attachments/assets/c0a834f1-47a2-49e0-9f87-fb5cfb6d78de">

<img width="260" alt="image" src="https://github.com/user-attachments/assets/7838a693-4f5e-473b-8646-5eb62a58e5d0">

**Comment by hydah** [comment]
Based on the SDKAppID you are using, it appears to be for TRTC China site. Please note that the WHIP feature is only available for accessing the international site.
